tap "getantibody/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "potatolabs/git-redate"
cask "adoptopenjdk8"
brew "bash"
brew "cairo"
brew "ccat"
brew "chezscheme"
brew "clisp"
brew "coreutils"
brew "dnsmasq", restart_service: true
brew "docker", link: false
brew "docker-machine", link: false
brew "duti"
brew "elasticsearch"
brew "elixir"
brew "exa"
brew "ffmpeg"
brew "ghi"
brew "git"
brew "gnu-sed"
brew "gnupg", link: false
brew "graphicsmagick"
brew "httpie"
brew "hub"
brew "memcached", restart_service: true
brew "minimal-racket"
brew "mit-scheme"
brew "neovim"
brew "nginx", restart_service: true
brew "nmap"
brew "node", link: false
brew "pdftk-java"
brew "pinentry-mac"
brew "postgresql"
brew "pyenv"
brew "redis", restart_service: true
brew "rust"
brew "sbcl"
brew "telnet"
brew "vault"
brew "watchman"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "getantibody/tap/antibody"
brew "heroku/brew/heroku"
brew "potatolabs/git-redate/git-redate"
cask "alfred"
cask "bartender"
cask "bettertouchtool"
cask "caffeine"
cask "chromium"
cask "cscreen"
cask "dash"
cask "discord"
cask "docker"
cask "firefox-developer-edition"
cask "font-hasklig-nerd-font"
cask "gitkraken"
cask "google-chrome-dev"
cask "insomnia"
cask "iterm2"
cask "java"
cask "microsoft-teams"
cask "mplayerx"
cask "notion"
cask "robo-3t"
cask "slack"
cask "slack-beta"
cask "spotify"
cask "sublime-text"
cask "telegram-desktop"
cask "tor-browser"
cask "transmission"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc-nightly"
