source $HOME/.config/zsh/environment.zsh

typeset -ga sources
sources+="$ZSH_CONFIG/environment.zsh"
sources+="$ZSH_CONFIG/private.zsh"
sources+="$ZSH_CONFIG/options.zsh"
sources+="$ZSH_CONFIG/prompt.zsh"
sources+="$ZSH_CONFIG/functions.zsh"
sources+="$ZSH_CONFIG/aliases.zsh"
sources+="$ZSH_CONFIG/completion.zsh"

# Check for a system specific file
systemFile=`uname -s | tr "[:upper:]" "[:lower:]"`
sources+="$ZSH_CONFIG/$systemFile.zsh"

#colors
#BASE16_SHELL="$HOME/dotfiles/base16-ocean.dark.sh"
#[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
#end colors

foreach file (`echo $sources`)
	if [[ -a $file ]]; then
		source $file
	fi
end

#antibody
source <(antibody init)
antibody bundle < $HOME/dotfiles/zsh/antibody/plugins.txt
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
#eval "$(jenv init -)"
eval "$(pyenv init --path)"
eval "$(rbenv init -)"
#eval "$(thefuck --alias)"

# OPAM configuration
. /Users/teddy/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

